// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ufclist

import (
	"database/sql"
)

type Fighter struct {
	ID       interface{}
	Name     string
	Age      uint8
	Nickname sql.NullString
}
