// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ufclist

import (
	"database/sql"
)

type Fighter struct {
	ID       int64
	Name     string
	Age      int64
	Nickname sql.NullString
}
